%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 3-day set comparison
clear A_idx A three_day_idx cond1 cond2 cond3 cond4 cond5 cond6
clear cond_brdf1 cond_brdf2 cond_brdf3
brdf_opt = 7;

for idx = 1:size(GOCI_DailyStatMatrix,2)-2
      cond_brdf1 = [GOCI_DailyStatMatrix(idx+0).brdf_opt]==brdf_opt;
      cond_brdf2 = [GOCI_DailyStatMatrix(idx+1).brdf_opt]==brdf_opt;
      cond_brdf3 = [GOCI_DailyStatMatrix(idx+2).brdf_opt]==brdf_opt;
      
      
      cond1 = ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_412_00]) && ... % the assumption that if at least one band is valid for that hour, the rest will be too!!! Maybe not true
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_412_01]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_412_02]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_412_03]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_412_04]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_412_05]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_412_06]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_412_07]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_412_00]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_412_01]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_412_02]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_412_03]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_412_04]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_412_05]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_412_06]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_412_07]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_412_00]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_412_01]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_412_02]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_412_03]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_412_04]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_412_05]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_412_06]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_412_07]);
      
      
      cond2 = ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_443_00]) && ... % the assumption that if at least one band is valid for that hour, the rest will be too!!! Maybe not true
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_443_01]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_443_02]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_443_03]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_443_04]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_443_05]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_443_06]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_443_07]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_443_00]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_443_01]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_443_02]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_443_03]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_443_04]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_443_05]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_443_06]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_443_07]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_443_00]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_443_01]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_443_02]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_443_03]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_443_04]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_443_05]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_443_06]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_443_07]);
      
      cond3 = ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_490_00]) && ... % the assumption that if at least one band is valid for that hour, the rest will be too!!! Maybe not true
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_490_01]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_490_02]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_490_03]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_490_04]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_490_05]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_490_06]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_490_07]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_490_00]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_490_01]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_490_02]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_490_03]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_490_04]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_490_05]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_490_06]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_490_07]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_490_00]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_490_01]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_490_02]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_490_03]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_490_04]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_490_05]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_490_06]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_490_07]);
      
      cond4 = ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_555_00]) && ... % the assumption that if at least one band is valid for that hour, the rest will be too!!! Maybe not true
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_555_01]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_555_02]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_555_03]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_555_04]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_555_05]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_555_06]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_555_07]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_555_00]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_555_01]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_555_02]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_555_03]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_555_04]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_555_05]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_555_06]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_555_07]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_555_00]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_555_01]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_555_02]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_555_03]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_555_04]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_555_05]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_555_06]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_555_07]);
      
      cond5 = ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_660_00]) && ... % the assumption that if at least one band is valid for that hour, the rest will be too!!! Maybe not true
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_660_01]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_660_02]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_660_03]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_660_04]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_660_05]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_660_06]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_660_07]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_660_00]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_660_01]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_660_02]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_660_03]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_660_04]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_660_05]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_660_06]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_660_07]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_660_00]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_660_01]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_660_02]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_660_03]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_660_04]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_660_05]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_660_06]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_660_07]);
      
      cond6 = ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_680_00]) && ... % the assumption that if at least one band is valid for that hour, the rest will be too!!! Maybe not true
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_680_01]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_680_02]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_680_03]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_680_04]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_680_05]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_680_06]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+0).Rrs_680_07]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_680_00]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_680_01]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_680_02]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_680_03]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_680_04]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_680_05]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_680_06]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+1).Rrs_680_07]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_680_00]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_680_01]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_680_02]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_680_03]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_680_04]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_680_05]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_680_06]) && ...
            ~isnan([GOCI_DailyStatMatrix(idx+2).Rrs_680_07]);
      
      if ~isempty(cond1)&&~isempty(cond2)&&~isempty(cond3)&&~isempty(cond4)&&~isempty(cond5)&&~isempty(cond6)...
                  &&~isempty(cond_brdf1)&&~isempty(cond_brdf2)&&~isempty(cond_brdf3)
            if cond1&&cond2&&cond3&&cond4&&cond5&&cond6... % for bands 412, 443, 490, and 555
                        &&cond_brdf1&&cond_brdf2&&cond_brdf3
                  three_day_idx(idx)=true;
                  
            else
                  three_day_idx(idx)=false;
            end
      else
            three_day_idx(idx)=false;
      end
end

A_idx= find(three_day_idx); % indeces to 3-day sequences.
%% 3-day sequences plot -- Rrs

% for idx = 1:1*sum(three_day_idx)/4
for idx = [find(A_idx==find([GOCI_DailyStatMatrix.datetime]==datetime(2012,07,28))) ...
            find(A_idx==find([GOCI_DailyStatMatrix.datetime]==datetime(2015,09,01)))]
      % for idx = 1:size(A,2)
      
      % Rrs
      tod_Rrs_412_00 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_412_00] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_412_00] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_412_00]];
      tod_Rrs_412_01 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_412_01] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_412_01] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_412_01]];
      tod_Rrs_412_02 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_412_02] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_412_02] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_412_02]];
      tod_Rrs_412_03 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_412_03] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_412_03] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_412_03]];
      tod_Rrs_412_04 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_412_04] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_412_04] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_412_04]];
      tod_Rrs_412_05 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_412_05] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_412_05] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_412_05]];
      tod_Rrs_412_06 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_412_06] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_412_06] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_412_06]];
      tod_Rrs_412_07 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_412_07] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_412_07] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_412_07]];
      
      tod_Rrs_443_00 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_443_00] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_443_00] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_443_00]];
      tod_Rrs_443_01 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_443_01] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_443_01] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_443_01]];
      tod_Rrs_443_02 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_443_02] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_443_02] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_443_02]];
      tod_Rrs_443_03 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_443_03] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_443_03] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_443_03]];
      tod_Rrs_443_04 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_443_04] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_443_04] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_443_04]];
      tod_Rrs_443_05 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_443_05] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_443_05] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_443_05]];
      tod_Rrs_443_06 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_443_06] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_443_06] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_443_06]];
      tod_Rrs_443_07 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_443_07] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_443_07] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_443_07]];
      
      tod_Rrs_490_00 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_490_00] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_490_00] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_490_00]];
      tod_Rrs_490_01 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_490_01] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_490_01] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_490_01]];
      tod_Rrs_490_02 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_490_02] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_490_02] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_490_02]];
      tod_Rrs_490_03 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_490_03] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_490_03] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_490_03]];
      tod_Rrs_490_04 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_490_04] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_490_04] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_490_04]];
      tod_Rrs_490_05 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_490_05] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_490_05] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_490_05]];
      tod_Rrs_490_06 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_490_06] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_490_06] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_490_06]];
      tod_Rrs_490_07 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_490_07] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_490_07] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_490_07]];
      
      tod_Rrs_555_00 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_555_00] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_555_00] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_555_00]];
      tod_Rrs_555_01 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_555_01] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_555_01] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_555_01]];
      tod_Rrs_555_02 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_555_02] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_555_02] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_555_02]];
      tod_Rrs_555_03 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_555_03] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_555_03] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_555_03]];
      tod_Rrs_555_04 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_555_04] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_555_04] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_555_04]];
      tod_Rrs_555_05 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_555_05] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_555_05] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_555_05]];
      tod_Rrs_555_06 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_555_06] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_555_06] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_555_06]];
      tod_Rrs_555_07 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_555_07] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_555_07] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_555_07]];
      
      tod_Rrs_660_00 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_660_00] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_660_00] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_660_00]];
      tod_Rrs_660_01 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_660_01] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_660_01] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_660_01]];
      tod_Rrs_660_02 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_660_02] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_660_02] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_660_02]];
      tod_Rrs_660_03 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_660_03] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_660_03] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_660_03]];
      tod_Rrs_660_04 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_660_04] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_660_04] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_660_04]];
      tod_Rrs_660_05 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_660_05] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_660_05] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_660_05]];
      tod_Rrs_660_06 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_660_06] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_660_06] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_660_06]];
      tod_Rrs_660_07 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_660_07] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_660_07] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_660_07]];
      
      tod_Rrs_680_00 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_680_00] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_680_00] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_680_00]];
      tod_Rrs_680_01 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_680_01] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_680_01] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_680_01]];
      tod_Rrs_680_02 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_680_02] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_680_02] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_680_02]];
      tod_Rrs_680_03 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_680_03] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_680_03] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_680_03]];
      tod_Rrs_680_04 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_680_04] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_680_04] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_680_04]];
      tod_Rrs_680_05 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_680_05] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_680_05] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_680_05]];
      tod_Rrs_680_06 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_680_06] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_680_06] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_680_06]];
      tod_Rrs_680_07 = [[GOCI_DailyStatMatrix(A_idx(idx)).Rrs_680_07] [GOCI_DailyStatMatrix(A_idx(idx)+1).Rrs_680_07] [GOCI_DailyStatMatrix(A_idx(idx)+2).Rrs_680_07]];
      

      % datetime
      tod_Rrs_412_00_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_412_01_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_412_02_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_412_03_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_412_04_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_412_05_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_412_06_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_412_07_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      
      tod_Rrs_443_00_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_443_01_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_443_02_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_443_03_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_443_04_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_443_05_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_443_06_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_443_07_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      
      tod_Rrs_490_00_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_490_01_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_490_02_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_490_03_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_490_04_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_490_05_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_490_06_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_490_07_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      
      tod_Rrs_555_00_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_555_01_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_555_02_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_555_03_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_555_04_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_555_05_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_555_06_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_555_07_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      
      tod_Rrs_660_00_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_660_01_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_660_02_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_660_03_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_660_04_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_660_05_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_660_06_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_660_07_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      
      tod_Rrs_680_00_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_680_01_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_680_02_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_680_03_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_680_04_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_680_05_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_680_06_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      tod_Rrs_680_07_datetime = [[GOCI_DailyStatMatrix(A_idx(idx)).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+1).datetime] [GOCI_DailyStatMatrix(A_idx(idx)+2).datetime]];
      
      
      fs = 30;
      lw = 1.5;
      ms = 16;
      h = figure('Color','white','DefaultAxesFontSize',fs,'Name',['n = ' num2str(A_idx(idx)) ';idx=' num2str(idx)]);
      set(gcf,'Units', 'Normalized', 'OuterPosition', [0 0 0.5 1]);
      set(gcf,'PaperPositionMode','auto'); %set paper pos for printing
      
      
      %% Rrs
      % Rrs_412
      % subplot(2,2,1)
      plot(tod_Rrs_412_00_datetime+hours(0),tod_Rrs_412_00,'-or','MarkerSize',ms,'LineWidth',lw)
      ylim([0 0.018])
      hold on
      plot(tod_Rrs_412_01_datetime+hours(1),tod_Rrs_412_01,'-og','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_412_02_datetime+hours(2),tod_Rrs_412_02,'-ob','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_412_03_datetime+hours(3),tod_Rrs_412_03,'-ok','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_412_04_datetime+hours(4),tod_Rrs_412_04,'-oc','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_412_05_datetime+hours(5),tod_Rrs_412_05,'-om','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_412_06_datetime+hours(6),tod_Rrs_412_06,'-o','Color',[1 0.5 0],'MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_412_07_datetime+hours(7),tod_Rrs_412_07,'-o','Color',[0.5 0 0.5],'MarkerSize',ms,'LineWidth',lw)
      
      % ylabel('R_{rs}(412) (sr^{-1})','FontSize',fs)
      % xlabel('Time','FontSize',fs)
      % legend('0h','1h','2h','3h','4h','5h','6h','7h','Location','northeast')
      
      % Rrs_443
      % subplot(2,2,1)
      plot(tod_Rrs_443_00_datetime+hours(0),tod_Rrs_443_00,'-^r','MarkerSize',ms,'LineWidth',lw)
      hold on
      plot(tod_Rrs_443_01_datetime+hours(1),tod_Rrs_443_01,'-^g','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_443_02_datetime+hours(2),tod_Rrs_443_02,'-^b','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_443_03_datetime+hours(3),tod_Rrs_443_03,'-^k','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_443_04_datetime+hours(4),tod_Rrs_443_04,'-^c','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_443_05_datetime+hours(5),tod_Rrs_443_05,'-^m','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_443_06_datetime+hours(6),tod_Rrs_443_06,'-^','Color',[1 0.5 0],'MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_443_07_datetime+hours(7),tod_Rrs_443_07,'-^','Color',[0.5 0 0.5],'MarkerSize',ms,'LineWidth',lw)
      
      % ylabel('R_{rs}(443) (sr^{-1})','FontSize',fs)
      % xlabel('Time','FontSize',fs)
      % legend('0h','1h','2h','3h','4h','5h','6h','7h','Location','northeast')
      
      % Rrs_490
      % subplot(2,2,1)
      plot(tod_Rrs_490_00_datetime+hours(0),tod_Rrs_490_00,'-*r','MarkerSize',ms,'LineWidth',lw)
      hold on
      plot(tod_Rrs_490_01_datetime+hours(1),tod_Rrs_490_01,'-*g','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_490_02_datetime+hours(2),tod_Rrs_490_02,'-*b','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_490_03_datetime+hours(3),tod_Rrs_490_03,'-*k','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_490_04_datetime+hours(4),tod_Rrs_490_04,'-*c','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_490_05_datetime+hours(5),tod_Rrs_490_05,'-*m','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_490_06_datetime+hours(6),tod_Rrs_490_06,'-*','Color',[1 0.5 0],'MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_490_07_datetime+hours(7),tod_Rrs_490_07,'-*','Color',[0.5 0 0.5],'MarkerSize',ms,'LineWidth',lw)
      
      % ylabel('R_{rs}(490) (sr^{-1})','FontSize',fs)
      % xlabel('Time','FontSize',fs)
      % legend('0h','1h','2h','3h','4h','5h','6h','7h','Location','northeast')
      
      % Rrs_555
      % subplot(2,2,1)
      plot(tod_Rrs_555_00_datetime+hours(0),tod_Rrs_555_00,'-xr','MarkerSize',ms,'LineWidth',lw)
      hold on
      plot(tod_Rrs_555_01_datetime+hours(1),tod_Rrs_555_01,'-xg','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_555_02_datetime+hours(2),tod_Rrs_555_02,'-xb','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_555_03_datetime+hours(3),tod_Rrs_555_03,'-xk','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_555_04_datetime+hours(4),tod_Rrs_555_04,'-xc','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_555_05_datetime+hours(5),tod_Rrs_555_05,'-xm','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_555_06_datetime+hours(6),tod_Rrs_555_06,'-x','Color',[1 0.5 0],'MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_555_07_datetime+hours(7),tod_Rrs_555_07,'-x','Color',[0.5 0 0.5],'MarkerSize',ms,'LineWidth',lw)
 
      % Rrs_660
      % subplot(2,2,1)
      plot(tod_Rrs_660_00_datetime+hours(0),tod_Rrs_660_00,'-xr','MarkerSize',ms,'LineWidth',lw)
      hold on
      plot(tod_Rrs_660_01_datetime+hours(1),tod_Rrs_660_01,'-xg','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_660_02_datetime+hours(2),tod_Rrs_660_02,'-xb','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_660_03_datetime+hours(3),tod_Rrs_660_03,'-xk','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_660_04_datetime+hours(4),tod_Rrs_660_04,'-xc','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_660_05_datetime+hours(5),tod_Rrs_660_05,'-xm','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_660_06_datetime+hours(6),tod_Rrs_660_06,'-x','Color',[1 0.5 0],'MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_660_07_datetime+hours(7),tod_Rrs_660_07,'-x','Color',[0.5 0 0.5],'MarkerSize',ms,'LineWidth',lw)

      % Rrs_680
      % subplot(2,2,1)
      plot(tod_Rrs_680_00_datetime+hours(0),tod_Rrs_680_00,'-xr','MarkerSize',ms,'LineWidth',lw)
      hold on
      plot(tod_Rrs_680_01_datetime+hours(1),tod_Rrs_680_01,'-xg','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_680_02_datetime+hours(2),tod_Rrs_680_02,'-xb','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_680_03_datetime+hours(3),tod_Rrs_680_03,'-xk','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_680_04_datetime+hours(4),tod_Rrs_680_04,'-xc','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_680_05_datetime+hours(5),tod_Rrs_680_05,'-xm','MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_680_06_datetime+hours(6),tod_Rrs_680_06,'-x','Color',[1 0.5 0],'MarkerSize',ms,'LineWidth',lw)
      plot(tod_Rrs_680_07_datetime+hours(7),tod_Rrs_680_07,'-x','Color',[0.5 0 0.5],'MarkerSize',ms,'LineWidth',lw)

      grid on
      ylabel('{\itR}_{rs}(\lambda) (sr^{-1})','FontSize',fs)
      xlabel('Time','FontSize',fs)
      
      datetick('x','mm/dd/yy')
      ax = gca;
      % ax.YLim(1) = 0 ;
      
      ax.XLim(1) = ax.XTick(1)-0.2;
      ax.XLim(2) = ax.XTick(3)+0.5;
      
      %       hleg = legend('412: 0h','412: 1h','412: 2h','412: 3h','412: 4h','412: 5h','412: 6h','412: 7h',...
      %             '443: 0h','443: 1h','443: 2h','443: 3h','443: 4h','443: 5h','443: 6h','443: 7h',...
      %             '490: 0h','490: 1h','490: 2h','490: 3h','490: 4h','490: 5h','490: 6h','490: 7h',...
      %             '555: 0h','555: 1h','555: 2h','555: 3h','555: 4h','555: 5h','555: 6h','555: 7h');
      %       set(hleg,'fontsize',22)
      %       set(hleg,'Location','bestoutside')
      
      set(gcf,'Units', 'Normalized', 'OuterPosition', [0 0 0.5 1]);
      set(gcf,'PaperPositionMode','auto'); %set paper pos for printing
      
      
      
end
%
figure(1)
hold on
h = gcf;
% annotations
% 412
annotation(h,'textbox',...
      [0.65 0.80 0.04 0.04],...
      'Color',[0.5 0 0.5],...
      'String',{'412'},...
      'FontSize',fs+2,...
      'FitBoxToText','off',...
      'EdgeColor',[1 1 1],...
      'BackgroundColor',[1 1 1]);

% 443
annotation(h,'textbox',...
      [0.65 0.65 0.04 0.04],...
      'Color',[0 0 1],...
      'String',{'443'},...
      'FontSize',fs+2,...
      'FitBoxToText','off',...
      'EdgeColor',[1 1 1],...
      'BackgroundColor',[1 1 1]);

% 490
annotation(h,'textbox',...
      [0.65 0.46 0.04 0.04],...
      'Color',[0 0.5 1],...
      'String',{'490'},...
      'FontSize',fs+2,...
      'FitBoxToText','off',...
      'EdgeColor',[1 1 1],...
      'BackgroundColor',[1 1 1]);

% 555
annotation(h,'textbox',...
      [0.65 0.22 0.04 0.04],...
      'Color',[0 0.5 0],...
      'String',{'555'},...
      'FontSize',fs+2,...
      'FitBoxToText','off',...
      'EdgeColor',[1 1 1],...
      'BackgroundColor',[1 1 1]);
%
figure(2)
hold on
h = gcf;
% annotations
% 412
annotation(h,'textbox',...
      [0.65 0.78 0.04 0.04],...
      'Color',[0.5 0 0.5],...
      'String',{'412'},...
      'FontSize',fs+2,...
      'FitBoxToText','off',...
      'EdgeColor',[1 1 1],...
      'BackgroundColor',[1 1 1]);

% 443
annotation(h,'textbox',...
      [0.65 0.60 0.04 0.04],...
      'Color',[0 0 1],...
      'String',{'443'},...
      'FontSize',fs+2,...
      'FitBoxToText','off',...
      'EdgeColor',[1 1 1],...
      'BackgroundColor',[1 1 1]);

% 490
annotation(h,'textbox',...
      [0.65 0.41 0.04 0.04],...
      'Color',[0 0.5 1],...
      'String',{'490'},...
      'FontSize',fs+2,...
      'FitBoxToText','off',...
      'EdgeColor',[1 1 1],...
      'BackgroundColor',[1 1 1]);

% 555
annotation(h,'textbox',...
      [0.65 0.19 0.04 0.04],...
      'Color',[0 0.5 0],...
      'String',{'555'},...
      'FontSize',fs+2,...
      'FitBoxToText','off',...
      'EdgeColor',[1 1 1],...
      'BackgroundColor',[1 1 1]);


savedirname = '/Users/jconchas/Documents/Latex/2017_GOCI_paper/Figures/source/';

saveas(gcf,[savedirname '3days_all_' num2str(idx)],'epsc')